openapi: 3.2.0
info:
  title: Crosswork Data Gateway Manager Troubleshooting Command API
  description: APIs to support CDG troubleshooting
  contact:
    name: Crosswork Team, Cisco
    email: support@cisco.com
  license:
    name: Cisco Software License Agreement
    url: http://www.cisco.com/public/sw-license-agreement.html
  version: 1.0.0
  x-provenance:
    method: harvested
    authored_by: Cisco Crosswork
    harvested_by: API Evangelist
    harvested_on: '2026-08-19'
    first_party: true
    note: Published by Cisco. Retrieved unmodified except for this x-provenance block.
    provider_published: true
  x-evidence:
  - type: source
    url: https://github.com/CiscoDevNet/crosswork-openapi-spec/blob/master/CDG/2.0APIs/cdg_troubleshooting_api.swagger.json
  - type: raw
    url: https://raw.githubusercontent.com/CiscoDevNet/crosswork-openapi-spec/master/CDG/2.0APIs/cdg_troubleshooting_api.swagger.json
servers:
- url: /crosswork/dg-manager
security:
- bearerAuth: []
tags:
- name: Command
paths:
  /v1/command/showtech:
    post:
      summary: Submits showtech command to collect CDG showtech logs
      operationId: SubmitShowtechCommand
      deprecated: false
      responses:
        '200':
          description: OK. The showtech log collection command got submitted. Use /v1/command/query to find out the status.
        '400':
          description: Bad Request. The request is malformed in some way and the server cannot process it.
          headers: {}
      requestBody:
        content:
          'application/json ':
            schema:
              $ref: '#/components/schemas/SubmitShowtechCommand'
        required: true
      tags:
      - Command
  /v1/command/reboot:
    post:
      summary: Submits reboot command to reboot CDG. Crosswork user with read, write privileges can submit reboot command.
      operationId: SubmitRebootCommand
      deprecated: false
      responses:
        '200':
          description: OK. The reboot data gateway command got submitted. Check the operational status of Data Gateway to determine it got rebooted.
          headers: {}
        '400':
          description: Bad Request. The request is malformed in some way and the server cannot process it.
      requestBody:
        content:
          'application/json ':
            schema:
              $ref: '#/components/schemas/SubmitRebootCommand'
        required: true
      tags:
      - Command
  /v1/command/query:
    post:
      summary: Gets CDG Showtech log collection status
      operationId: ShowtechStatusRequest
      deprecated: false
      responses:
        '200':
          description: 'OK. The request was successful. The status is contained in the response body. Once the data gateway showtech log collection is successful. The response contains the downloadable link of the showtech log file. '
          headers: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShowtechStatusRequest'
        required: true
      tags:
      - Command
components:
  schemas:
    Value:
      title: Value
      example:
        str: test1234
      type: object
      properties:
        str:
          type: string
      required:
      - str
    Value1:
      title: Value1
      example:
        valueStr: '5065'
      type: object
      properties:
        valueStr:
          type: string
      required:
      - valueStr
    SubmitShowtechCommand:
      title: ShowtechCommandPayload
      example:
        id: '5065'
        commandName: SHOW_TECH_SUPPORT
        clientId:
          uuid: d58de587-5da2-4a62-b010-32395acc8dbc
        args:
        - key: passphrase
          value:
            str: test1234
      type: object
      properties:
        id:
          type: string
        commandName:
          type: string
        clientId:
          $ref: '#/components/schemas/ClientId'
        args:
          type: array
          items:
            $ref: '#/components/schemas/Arg'
      required:
      - id
      - commandName
      - clientId
      - args
    ClientId:
      title: ClientId
      example:
        uuid: d58de587-5da2-4a62-b010-32395acc8dbc
      type: object
      properties:
        uuid:
          type: string
      required:
      - uuid
    Arg:
      title: Arg
      example:
        key: passphrase
        value:
          str: test1234
      type: object
      properties:
        key:
          type: string
        value:
          $ref: '#/components/schemas/Value'
      required:
      - key
      - value
    SubmitRebootCommand:
      title: RebootCommandPayload
      example:
        id: '3003'
        commandName: REBOOT_VM
        clientId:
          uuid: c9582aba-456c-43b7-aab0-605e28c6f131
      type: object
      properties:
        id:
          type: string
        commandName:
          type: string
        clientId:
          $ref: '#/components/schemas/ClientId'
      required:
      - id
      - commandName
      - clientId
    QueryParam:
      title: QueryParam
      example:
        field: CMDID
        value:
          valueStr: '5065'
      type: object
      properties:
        field:
          type: string
        value:
          $ref: '#/components/schemas/Value1'
      required:
      - field
      - value
    ShowtechStatusRequest:
      title: ShowtechStatusRequest
      example:
        queryParams:
        - field: CMDID
          value:
            valueStr: '5065'
      type: object
      properties:
        queryParams:
          type: array
          items:
            $ref: '#/components/schemas/QueryParam'
      required:
      - queryParams
  securitySchemes:
    bearerAuth:
      type: apiKey
      name: Authorization
      in: header
